name: ci

on:
  push:
    # branches:
    # - main
    # - release/*
  pull_request:
    branches:
    - main
    - dev
  workflow_dispatch:

# Needed for micromamba pickup
defaults:
  run:
    shell: bash -l {0}

jobs:
  test:

    # Setup the Python that the ROOT binary was built against
    runs-on: ${{ matrix.os }}
    # # On push events run the CI only on main by default, but run on any branch if the commit message contains '[ci all]'
    # if: >-
    #   github.event_name != 'push'
    #   || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    #   || (github.event_name == 'push' && github.ref != 'refs/heads/main' && contains(github.event.head_commit.message, '[ci all]'))
    strategy:
      matrix:
        os: [ubuntu-latest]
        root-version: ["6.24", "6.26"]
        python-version: ["3.8", "3.9", "3.10"]
        exclude:
          - root-version: "6.24"
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba environment
      uses: mamba-org/provision-with-micromamba@v15
      with:
        environment-file: false
        environment-name: ci
        extra-specs: |
          python=${{ matrix.python-version }}
          root=${{ matrix.root-version }}
          libzlib
          zlib
          pip
        channels: conda-forge

    - name: ROOT info
      run: |
        root-config --version
        root-config --python-version

    # Install dependencies
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade -r requirements.txt
        echo $PWD && cd validation
        python -m pip install --upgrade .

    - name: List installed dependencies
      run: python -m pip list

    - name: Print help message
      run: |
        echo $PWD
        ls -lhtra
        ./validation/scripts/validation_bootstrap --help

    - name: Validate Parton-Level analyses
      run: |
        ./validation/scripts/validation_bootstrap --parton-level

    - name: Validate Hadron-Level analyses
      run: |
        ./validation/scripts/validation_bootstrap --hadron-level

    - name: Validate Reco-Level analyses
      run : |
        ./validation/scripts/validation_bootstrap --reco-level

    #- name : Validate Expert mode
    #  run : |
    #    ./validation/scripts/validation_bootstrap --expert-mode

    - name : Validate FastJet interface
      run : |
        ./validation/scripts/validation_bootstrap --fastjet
